Repository RocketMeet/RocketMeet-mailer, pull requests merged in 2021-03, with the labels that each got.

#23 Add ESLint errors checker action setup for PRs
  .github/workflows/lint.yml
Labels: Level2, gssoc21

#22 ✨ Added PollResponse API
  src/routes/v1/index.ts
  src/routes/v1/pollResponse.ts
  template/pollResponse.html
Labels: Level3, enhancement, gssoc21

#26 Add instruction to lint code
  README.md
Labels: Level0, gssoc21
